import localFont from "next/font/local";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils";

// // Font files can be colocated inside of `app`
// const gilroy = localFont({
//   src: [
//     // { path: "../fonts/Gilroy-ExtraBold.otf" },
//     { path: "../fonts/Gilroy-Light.otf" },
//   ],
// });

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("font-gilroy-italic, text-black")}>{children}</body>
    </html>
  );
}
